### ISSUE TITLE
[Content Request]: frcdesign.org

### ISSUE THREAD

**Issue by coulterbailey09** [LynkRobotics/Lynk-Library-of-Knowledge#339]
### Name of Resource

frc design

### Resource Link 1

https://www.frcdesign.org/

### Resource Link 2

www.youtube.com/@howlongismydesign

### Subteam

Design

### Level of content

Tools

### Reading / Video / Other

Reading, Video, Other

### Have you checked if this resource is already in the LLK

- [X] I have checked

**Comment by witherslayer67** [comment]
Thanks for the submission! It has been added onto [The design page of the LLK](https://docs.lynkrobotics.org/design/index.html)
