### ISSUE TITLE
[Content Request]: 254 2023 Technical Binder

### ISSUE THREAD

**Issue by Shuki01** [LynkRobotics/Lynk-Library-of-Knowledge#99]
### Name of Resource

254: 2023

### Resource Link

https://media.team254.com/2023/10/90bc07c6-2023-Tech-Binder-V6.pdf

### Subteam

Technical Binders

### Level of content

Misc

### Reading / Video / Other

Reading

### Have you checked if this resource is already in the LLK

- [X] I have checked

**Comment by witherslayer67** [comment]
added 👍
